<?php

namespace ContainerHUcQBcg;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCalculatorControllerService extends App_KernelTestDebugContainer
{
    /**
     * Gets the public 'App\Controller\CalculatorController' shared autowired service.
     *
     * @return \App\Controller\CalculatorController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/framework-bundle/Controller/AbstractController.php';
        include_once \dirname(__DIR__, 4).'/src/Controller/CalculatorController.php';

        $container->services['App\\Controller\\CalculatorController'] = $instance = new \App\Controller\CalculatorController();

        $instance->setContainer(($container->privates['.service_locator.W9y3dzm'] ?? $container->load('get_ServiceLocator_W9y3dzmService'))->withContext('App\\Controller\\CalculatorController', $container));

        return $instance;
    }
}
