<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerHUcQBcg\App_KernelTestDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerHUcQBcg/App_KernelTestDebugContainer.php') {
    touch(__DIR__.'/ContainerHUcQBcg.legacy');

    return;
}

if (!\class_exists(App_KernelTestDebugContainer::class, false)) {
    \class_alias(\ContainerHUcQBcg\App_KernelTestDebugContainer::class, App_KernelTestDebugContainer::class, false);
}

return new \ContainerHUcQBcg\App_KernelTestDebugContainer([
    'container.build_hash' => 'HUcQBcg',
    'container.build_id' => 'dd0089ee',
    'container.build_time' => 1624641726,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerHUcQBcg');
